this._s=this._s||{};(function(_){var window=this;
try{
_.m("b4xCIb");
var Uje=function(a){_.A.call(this,a.Ka);this.oa=this.Ca("BE25u");this.contents=this.Ca("BPrWId")};_.B(Uje,_.A);Uje.Ea=_.A.Ea;Uje.prototype.ka=function(){this.oa.Db().style.visibility=48<this.contents.Db().offsetHeight?"inherit":"hidden"};_.M(Uje.prototype,"z9RAXb",function(){return this.ka});_.xs(_.r7a,Uje);
_.p();
}catch(e){_._DumpException(e)}
try{
var czd;czd=function(a,b){for(var c=0;c<a.length;++c){var d=_.Pc(a[c],b);if(d){d=d.match(/\S+/g)||[];for(var e=0;e<d.length;e++)"img.l"===d[e]&&_.Ve(a[c],_.bw)}}};_.dzd=function(a){a=_.Xz(["xpdxpnd","mod"],a);czd(a,"cact")};_.ezd=function(a){a=_.Xz(["xpdxpnd","mod"],a);czd(a,"eact")};
_.fzd=function(a,b,c,d,e){function f(h,k){h=_.$a(h);for(var n=h.next();!n.done;n=h.next())n=n.value,_.Ff(n,"nlvc")||_.Oc(n)&&g.push(new _.Tn(n,k))}if(!_.Ff(b,"nlvc")){var g=[];"expanding"===c?(f(d,"show"),f(e,"hide"),b=1):(f(d,"hide"),f(e,"show"),b=2);_.Kw(g,{triggerElement:a||void 0,interactionContext:b,data:{ct:"knowledge_expander_toggle",cad:c}})}};_.Yz=function(a){return _.Rm.contains(a,"xpdopen")};_.Zz=function(a){return _.qm(a,"xpdbox")};
_.Xz=function(a,b){var c=[];a=b.querySelectorAll("."+a.join(", ."));for(var d=0;d<a.length;++d)_.Zz(a[d])===b&&c.push(a[d]);return c};_.gzd=function(a){a=_.Xz(["vk_arc"],a);return 0<a.length?a[0]:null};_.hzd=function(a,b){_.z.hb(a,b);(a=_.Zz(a))&&(b?_.Pn(a,"nlvc"):_.Nn(a,"nlvc","1"))};
_.izd=function(a,b){var c=_.gzd(a);if(null!==c||a.querySelector("[data-inside-content-expander-position]"))null!==c&&(_.Xm(c,"expanded",b?"true":"false"),c.hasAttribute("aria-label")&&_.an(c,b?"Show less":"Show more")),c="."+(b?"xpdclps":"xpdxpnd"),_.Sa(a.querySelectorAll("."+(b?"xpdxpnd":"xpdclps")),function(d){_.Ym(d,"hidden")}),_.Sa(a.querySelectorAll(c),function(d){_.Xm(d,"hidden",!0)})};_.jzd=function(a,b){return(b=b?b.srcElement||b.target:null)&&b!==a&&_.pm(b,"LI","bili")?!1:!0};
_.kzd=function(a){var b=a.event;a=a.actionElement.el();var c=_.qe(b);c&&(b=c);return _.jzd(a,b)};_.lzd=function(a,b){if(b){var c=_.Xz(["vk_ard"],a);c=0<c.length?c[0]:null}else c=_.Xz(["vk_aru"],a),c=0<c.length?c[0]:null;c&&_.Rm.xt(c,b?"vk_ard":"vk_aru",b?"vk_aru":"vk_ard");_.izd(a,b)};
}catch(e){_._DumpException(e)}
try{
var qzd;qzd=function(a){var b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};_.aA=function(a,b,c){_.Mg.call(this);this.Fg=null;this.oa=!1;this.DN=a;this.wa=c;this.ka=b||window;this.Qv=(0,_.Gg)(this.Pnc,this)};_.Lg(_.aA,_.Mg);_.l=_.aA.prototype;
_.l.start=function(){this.stop();this.oa=!1;var a=rzd(this),b=szd(this);a&&!b&&this.ka.mozRequestAnimationFrame?(this.Fg=_.Xd(this.ka,"MozBeforePaint",this.Qv),this.ka.mozRequestAnimationFrame(null),this.oa=!0):this.Fg=a&&b?a.call(this.ka,this.Qv):this.ka.setTimeout(qzd(this.Qv),20)};_.l.stop=function(){if(this.isActive()){var a=rzd(this),b=szd(this);a&&!b&&this.ka.mozRequestAnimationFrame?_.jl(this.Fg):a&&b?b.call(this.ka,this.Fg):this.ka.clearTimeout(this.Fg)}this.Fg=null};
_.l.fire=function(){this.stop();this.Pnc()};_.l.isActive=function(){return null!=this.Fg};_.l.Pnc=function(){this.oa&&this.Fg&&_.jl(this.Fg);this.Fg=null;this.DN.call(this.wa,_.Ig())};_.l.Ac=function(){this.stop();_.aA.Pd.Ac.call(this)};
var rzd=function(a){a=a.ka;return a.requestAnimationFrame||a.webkitRequestAnimationFrame||a.mozRequestAnimationFrame||a.oRequestAnimationFrame||a.msRequestAnimationFrame||null},szd=function(a){a=a.ka;return a.cancelAnimationFrame||a.cancelRequestAnimationFrame||a.webkitCancelRequestAnimationFrame||a.mozCancelRequestAnimationFrame||a.oCancelRequestAnimationFrame||a.msCancelRequestAnimationFrame||null};
}catch(e){_._DumpException(e)}
try{
_.m("QE1bwd");
_.HAd=function(a,b,c){_.Mg.call(this);var d=this;this.container=a;this.wa=[];this.Aa=null;this.ka=this.container.Jda();this.wa.push(_.Vz.subscribe("iehc",function(e){return _.GAd(d,e)}));this.container.wga()&&this.wa.push(_.Vz.subscribe("r",function(e){d.ka===e&&d.container.s7(d.container.xd())}));this.Ba=b||1;this.oa=c||0};_.B(_.HAd,_.Mg);_.HAd.prototype.Ac=function(){_.Sa(this.wa,_.Wz);_.Mg.prototype.Ac.call(this)};
_.HAd.prototype.expand=function(){this.container.d$()?IAd(this,!0):(this.container.s7(!0),this.container.M0(),_.GAd(this,this.ka,_.JAd(this)))};_.HAd.prototype.collapse=function(){this.container.d$()?IAd(this,!1):(this.container.s7(!1),this.container.NV(),_.KAd(this),_.GAd(this,this.ka,_.JAd(this)))};
var IAd=function(a,b){(new _.aA(function(){b||_.KAd(a);a.container.s7(b);LAd(a,b);_.GAd(a,a.ka,_.JAd(a))})).start();a.Aa=Date.now()},MAd=function(a,b){b?(a.oa+=1,a.container.M0()):(a.oa=0,a.container.NV())},LAd=function(a,b){var c=a.container.V0b();c.find(function(d,e){if(a.container.dWa(d)||b&&1<a.Ba&&a.oa>e&&e<c.length-1)return!1;d=_.z.getComputedStyle(d,"transitionDuration");return""!==d&&"none"!==d&&"0s"!==d})?(0,_.Je)(function(){MAd(a,b)},300):MAd(a,b)};
_.HAd.prototype.zG=function(){return null!=this.Aa&&this.Aa+300>Date.now()};_.KAd=function(a){var b=a.container.W8a();b=b?b.getBoundingClientRect().top-8:a.ka.getBoundingClientRect().bottom-8;a.container.d$()&&(b-=_.JAd(a));0>b&&(0,_.uz.by)(0,b)};_.JAd=function(a){var b=0;_.Sa(a.container.d0b(),function(c){a.container.g6b(c)?b+=c.scrollHeight:a.container.C5b(c)&&(b-=c.scrollHeight)},a);return b};
_.GAd=function(a,b,c){if(_.af(a.ka,b)){var d=_.pm(b,"g-expandable-content");if(d&&!a.container.dWa(d)&&0!==NAd(d)){var e=a.container.xd();if(e&&a.container.g6b(d)||!e&&a.container.C5b(d))a=d.scrollHeight,a=c?a+c:a+b.scrollHeight,_.z.setStyle(d,"max-height",a+"px")}}};_.OAd=function(a,b,c){return new _.HAd(a,void 0===b?1:b,void 0===c?0:c)};var rA=function(a){_.A.call(this,a.Ka);this.items=[];this.sC=[];this.Ia=null;this.actions=[];this.wa=null;this.Ba=!1;this.Aa=[];this.Na=this.getData("quie").Fb();this.La=this.getData("anim").Fb();this.Ta=this.getData("fcss").Fb();this.S8c=this.getData("rspae").Fb();this.Sa=this.getData("fae").Fb();this.oa=this.getData("npd").number(1);this.ka=this.getData("iexp").Fb()?this.oa:0;a=this.oa;var b=this.ka;this.Da=_.OAd(this,void 0===a?1:a,void 0===b?0:b);this.V1c=this.getData("slct").string("mnr-c")};
_.B(rA,_.A);rA.Ea=_.A.Ea;_.l=rA.prototype;_.l.ACe=function(){return this.Aa};_.l.xqd=function(){return this.Na};_.l.qAe=function(){return this.V1c};_.l.Ip=function(a){var b=this;PAd(this,this.getController(a.event.target).then(function(c){b.items.push(c);c.xd()!==b.xd()&&c.toggle()}))};_.l.rjf=function(a){var b=this;PAd(this,this.getController(a.event.target).then(function(c){b.Ia=c}));QAd(this)};
_.l.pjf=function(a){var b=this,c=a.event.target;PAd(this,this.getController(c).then(function(d){c.__mt=d.Ppa();c.__eb=d.Zia();b.La||_.z.setStyle(c,"transition","none");b.sC.push(d)}));QAd(this)};_.l.hjf=function(a){var b=this;PAd(this,this.getController(a.event.target).then(function(c){b.actions.push(c)}))};var PAd=function(a,b){a.Aa.push(b)};_.l=rA.prototype;_.l.yqd=function(a){RAd(this,a)&&this.toggle()};_.l.Tpe=function(a){RAd(this,a)&&this.expand()};_.l.cke=function(a){RAd(this,a)&&this.collapse()};
_.l.toggle=function(){this.Qja()?this.collapse():this.expand()};_.l.Qja=function(){return this.ka>=this.oa};_.l.expand=function(){var a=this;this.ka>=this.oa||this.Ba&&this.Da.zG()||_.bf(this.Aa).then(function(){a.Aa.length=0;a.Ba=!0;a.Da.expand()})};_.l.collapse=function(){var a=this;this.ka<this.oa||this.Ba&&this.Da.zG()||_.bf(this.Aa).then(function(){a.Aa.length=0;a.Ba=!0;a.Da.collapse()})};_.l.xd=function(){return 0<this.ka};_.l.d$=function(){return this.La};
_.l.wga=function(){return!this.Na||this.Ta};_.l.Isf=function(){return this.S8c};_.l.M0=function(){this.ka+=1;this.Ba=!1;SAd(this);for(var a=_.$a(this.actions),b=a.next();!b.done;b=a.next())b.value.agg();this.trigger(_.mzd,{bJ:this.wa});TAd(this,this.wa,"expanding");this.wa=null;this.Sa&&(a=_.qlc(this.getRoot().el(),_.nm))&&a.focus()};
_.l.NV=function(){this.ka=0;this.Ba=!1;SAd(this);for(var a=_.$a(this.actions),b=a.next();!b.done;b=a.next())b.value.geg();this.trigger(_.nzd,{bJ:this.wa});TAd(this,this.wa,"collapsing");this.wa=null};_.l.s7=function(a){1>=this.oa&&(this.ka=a?this.oa:0);for(var b=_.$a(this.items),c=b.next();!c.done;c=b.next())c=c.value,a?c.expand():c.collapse()};
var QAd=function(a){_.bf(a.Aa).then(function(){var b=a.W8a();if(b){var c=a.d0b().filter(function(d){return d.id}).map(function(d){return d.id});b.setAttribute("aria-controls",c.join(" "))}})};_.l=rA.prototype;_.l.Jda=function(){return this.getRoot().el()};_.l.V8a=function(){return this.Ca("gI9xcc").el()};_.l.d5=function(){return _.hp(this,"AHe6Kc").el()};_.l.sRc=function(){return _.hp(this,"bnBfGc").el()};_.l.W8a=function(){return this.Ia?this.Ia.getRoot().el():null};
_.l.V0b=function(){for(var a=[],b=_.$a(this.sC),c=b.next();!c.done;c=b.next())c=c.value,0!==c.Ppa()&&a.push(c.getRoot().el());return a};_.l.d0b=function(){return[].concat(_.cd(UAd(this,0)),_.cd(UAd(this,1)))};_.l.jEe=function(a){return this.Ia?this.Ia.G1b(a):[]};var NAd=function(a){return void 0!==a.__mt?a.__mt:0};_.l=rA.prototype;_.l.fYe=function(a){return 3===NAd(a)};_.l.vXe=function(a){return 2===NAd(a)};_.l.g6b=function(a){return 0===VAd(a)};_.l.C5b=function(a){return 1===VAd(a)};
_.l.dWa=function(a){return 2===VAd(a)};var VAd=function(a){return void 0!==a.__eb?a.__eb:2},SAd=function(a){a.Jda().setAttribute("aria-expanded",String(a.Qja()))},TAd=function(a,b,c){if(!b||_.Oc(b)){var d=UAd(a,0),e=UAd(a,1);_.fzd(b,a.Jda(),c,d,e)}},RAd=function(a,b){return _.kzd(b)?(a.wa=b.event.target,!0):!1},UAd=function(a,b){var c=[];a=_.$a(a.sC);for(var d=a.next();!d.done;d=a.next())d=d.value,d.Zia()===b&&c.push(d.getRoot().el());return c};rA.prototype.Kb=function(){this.Da.dispose()};
_.M(rA.prototype,"k4Iseb",function(){return this.Kb});_.M(rA.prototype,"em9Kzd",function(){return this.d0b});_.M(rA.prototype,"Y4cWJb",function(){return this.V0b});_.M(rA.prototype,"kgs1Xc",function(){return this.W8a});_.M(rA.prototype,"nKoqoe",function(){return this.sRc});_.M(rA.prototype,"zRB1Df",function(){return this.d5});_.M(rA.prototype,"hOh3bf",function(){return this.V8a});_.M(rA.prototype,"qrngke",function(){return this.Jda});_.M(rA.prototype,"Yzm1wf",function(){return this.NV});
_.M(rA.prototype,"sMv6wf",function(){return this.M0});_.M(rA.prototype,"FoYd",function(){return this.Isf});_.M(rA.prototype,"iGSKCe",function(){return this.wga});_.M(rA.prototype,"rXu79",function(){return this.d$});_.M(rA.prototype,"sMVRZe",function(){return this.xd});_.M(rA.prototype,"vhaaFf",function(){return this.collapse});_.M(rA.prototype,"KoToPc",function(){return this.expand});_.M(rA.prototype,"ZhEbuc",function(){return this.Qja});_.M(rA.prototype,"ornU0b",function(){return this.toggle});
_.M(rA.prototype,"fW2qAb",function(){return this.cke});_.M(rA.prototype,"AvkpRc",function(){return this.Tpe});_.M(rA.prototype,"yELBLe",function(){return this.yqd});_.M(rA.prototype,"Z6bwpe",function(){return this.hjf});_.M(rA.prototype,"AgioGc",function(){return this.pjf});_.M(rA.prototype,"GsRPff",function(){return this.rjf});_.M(rA.prototype,"Nh5q2c",function(){return this.Ip});_.M(rA.prototype,"vcEgJc",function(){return this.qAe});_.M(rA.prototype,"MT9BLc",function(){return this.xqd});
_.M(rA.prototype,"d74pFb",function(){return this.ACe});_.xs(_.r8a,rA);

_.p();
}catch(e){_._DumpException(e)}
try{
_.m("N8Q1ib");
var SDv=function(a){_.A.call(this,a.Ka)};_.B(SDv,_.A);SDv.Ea=_.A.Ea;SDv.prototype.Ic=function(a){_.To(a.event)};_.M(SDv.prototype,"h5M12e",function(){return this.Ic});_.xs(_.Bzb,SDv);
_.p();
}catch(e){_._DumpException(e)}
try{
_.rNu=_.K("XGRTMd");
}catch(e){_._DumpException(e)}
try{
_.m("XN4wKf");
var UDv=function(a){_.A.call(this,a.Ka)};_.B(UDv,_.A);UDv.Ea=_.A.Ea;UDv.prototype.ka=function(){var a=this.getRoot().closest(_.Co("Lv2Cle")).el();_.Ve(a,_.rNu);this.getRoot().hide();_.Kw([new _.Tn(this.getRoot().el(),"hide")]);_.Lw(this.getRoot().el());a=a.getElementsByClassName("aQ9ZH")[0];(0,_.z.hb)(a,!0);_.Kw([new _.Tn(a,"show")]);return!1};_.M(UDv.prototype,"in3Ghc",function(){return this.ka});_.xs(_.Dzb,UDv);
_.p();
}catch(e){_._DumpException(e)}
})(this._s);
// Google Inc.
